http:
  middlewares:
    redirect-to-https-local:
      redirectScheme:
        scheme: https
        port: "8444"
        permanent: true

  routers:
    traefik:
      rule: "Host(`traefik.universidad.localhost`)"
      entryPoints:
        - https
      service: "api@internal"
      tls:
        domains:
          - main: "universidad.localhost"
            sans:
              - "*.universidad.localhost"
          - main: "universidad.local"
            sans:
              - "*.universidad.local"

    hockey-local-https:
      rule: "Host(`localhost`) || Host(`127.0.0.1`)"
      entryPoints:
        - https
      tls: {}
      service: hockey

    hockey-local-http:
      rule: "Host(`localhost`) || Host(`127.0.0.1`)"
      entryPoints:
        - http
      middlewares:
        - redirect-to-https-local
      service: hockey

  services:
    hockey:
      loadBalancer:
        servers:
          - url: "http://app:5000"

tls:
  certificates:
    - certFile: "/etc/certs/cert.pem"
      keyFile: "/etc/certs/key.pem"
