"""create missing core tables

Revision ID: 8f9bfd237692
Revises: e1f2a3b4c5d6
Create Date: 2025-10-31 20:11:48.321566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9bfd237692'
down_revision = 'e1f2a3b4c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clubes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=True),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('cancha_local', sa.String(length=100), nullable=True),
    sa.Column('domicilio', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('web', sa.String(length=150), nullable=True),
    sa.Column('arbitro_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Resultados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_local', sa.String(length=100), nullable=False),
    sa.Column('club_visitante', sa.String(length=100), nullable=False),
    sa.Column('goles_local', sa.Integer(), nullable=False),
    sa.Column('goles_visitante', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arbitros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noticia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['Clubes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Jugadoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['Clubes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('is_operador', sa.Boolean(), nullable=False),
    sa.Column('puede_cargar_incidencias', sa.Boolean(), nullable=False),
    sa.Column('puede_precargar_equipos', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['Clubes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('fecha_numero', sa.Integer(), nullable=True),
    sa.Column('bloque', sa.String(length=5), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('cancha', sa.String(length=100), nullable=True),
    sa.Column('club_local_id', sa.Integer(), nullable=False),
    sa.Column('club_visitante_id', sa.Integer(), nullable=False),
    sa.Column('equipo_local_id', sa.Integer(), nullable=True),
    sa.Column('equipo_visitante_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('goles_local', sa.Integer(), nullable=True),
    sa.Column('goles_visitante', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_local_id'], ['Clubes.id'], ),
    sa.ForeignKeyConstraint(['club_visitante_id'], ['Clubes.id'], ),
    sa.ForeignKeyConstraint(['equipo_local_id'], ['Equipos.id'], ),
    sa.ForeignKeyConstraint(['equipo_visitante_id'], ['Equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Incidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('jugadora_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('minuto', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['Clubes.id'], ),
    sa.ForeignKeyConstraint(['jugadora_id'], ['Jugadoras.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['Partidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NotasPartido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['partido_id'], ['Partidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partido_id')
    )
    op.create_table('PrecargaJugadoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('jugadora_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['Clubes.id'], ),
    sa.ForeignKeyConstraint(['jugadora_id'], ['Jugadoras.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['Partidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partido_id', 'club_id', 'jugadora_id', name='uq_precarga_partido_club_jugadora')
    )
    op.create_table('arbitro_partido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('arbitro_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['arbitro_id'], ['arbitros.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['Partidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partido_id', 'arbitro_id', name='uq_arbitro_partido_arbitro')
    )
    with op.batch_alter_table('cuerpo_tecnico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cuerpo_tecnico_club_id'))
        batch_op.create_foreign_key(None, 'Clubes', ['club_id'], ['id'])

    with op.batch_alter_table('cuerpo_tecnico_partido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ct_partido_club_id'))
        batch_op.drop_index(batch_op.f('ix_ct_partido_partido_id'))
        batch_op.drop_constraint(batch_op.f('fk_ct_partido_ct'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Partidos', ['partido_id'], ['id'])
        batch_op.create_foreign_key(None, 'Clubes', ['club_id'], ['id'])
        batch_op.create_foreign_key(None, 'cuerpo_tecnico', ['cuerpo_tecnico_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuerpo_tecnico_partido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ct_partido_ct'), 'cuerpo_tecnico', ['cuerpo_tecnico_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_ct_partido_partido_id'), ['partido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ct_partido_club_id'), ['club_id'], unique=False)

    with op.batch_alter_table('cuerpo_tecnico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_cuerpo_tecnico_club_id'), ['club_id'], unique=False)

    op.drop_table('arbitro_partido')
    op.drop_table('PrecargaJugadoras')
    op.drop_table('NotasPartido')
    op.drop_table('Incidencias')
    op.drop_table('Partidos')
    op.drop_table('usuarios')
    op.drop_table('Jugadoras')
    op.drop_table('Equipos')
    op.drop_table('noticia')
    op.drop_table('arbitros')
    op.drop_table('Resultados')
    op.drop_table('Clubes')
    # ### end Alembic commands ###
