"""Make usuarios.club_id nullable and add operator permissions

Revision ID: bb38acd6bd8d
Revises: d9a1f2b3c4e5
Create Date: 2025-10-30 11:00:20.623035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from contextlib import suppress

# revision identifiers, used by Alembic.
revision = 'bb38acd6bd8d'
down_revision = 'd9a1f2b3c4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Reflejar índices y constraints existentes para evitar dropear los que no existen
    bind = op.get_bind()
    insp = sa.inspect(bind)

    # Helper para verificar existencia de tablas con mayúsculas usando to_regclass
    def regclass_exists(qualified_name: str) -> bool:
        try:
            return bool(bind.execute(sa.text("SELECT to_regclass(:n) IS NOT NULL"), {"n": qualified_name}).scalar())
        except Exception:
            return False

    # Resolver nombre real de la tabla respetando mayúsculas/minúsculas
    table_names = {name.lower(): name for name in (insp.get_table_names() + insp.get_table_names(schema='public'))}
    incidencias_table = table_names.get('incidencias', 'Incidencias')

    existing_idxs = set()
    existing_fks = set()
    try:
        existing_idxs = {ix['name'] for ix in insp.get_indexes(incidencias_table, schema='public')}
    except Exception:
        pass
    try:
        existing_fks = {fk['name'] for fk in insp.get_foreign_keys(incidencias_table, schema='public') if fk.get('name')}
    except Exception:
        pass

    # Solo alterar Incidencias si la tabla existe; si no existe, se tratará en una migración de creación inicial
    if regclass_exists('public."Incidencias"'):
        with op.batch_alter_table('Incidencias', schema=None) as batch_op:
            # Dropear sólo si existen para evitar fallos en bases limpias
            for idx_name in ('idx_incidencias_club', 'idx_incidencias_jugadora', 'idx_incidencias_partido'):
                if idx_name in existing_idxs:
                    batch_op.drop_index(idx_name)
            for fk_name in ('Incidencias_club_id_fkey', 'Incidencias_partido_id_fkey', 'Incidencias_jugadora_id_fkey'):
                if fk_name in existing_fks:
                    batch_op.drop_constraint(fk_name, type_='foreignkey')
            batch_op.create_foreign_key(None, 'Clubes', ['club_id'], ['id'])
            batch_op.create_foreign_key(None, 'Partidos', ['partido_id'], ['id'])
            batch_op.create_foreign_key(None, 'Jugadoras', ['jugadora_id'], ['id'])

    if regclass_exists('public."NotasPartido"'):
        with op.batch_alter_table('NotasPartido', schema=None) as batch_op:
            with suppress(Exception):
                batch_op.drop_index('idx_notas_partido')
            with suppress(Exception):
                batch_op.drop_index(batch_op.f('idx_notas_partido'))
            with suppress(Exception):
                batch_op.drop_constraint('NotasPartido_partido_id_fkey', type_='foreignkey')
            with suppress(Exception):
                batch_op.drop_constraint(batch_op.f('NotasPartido_partido_id_fkey'), type_='foreignkey')
            batch_op.create_foreign_key(None, 'Partidos', ['partido_id'], ['id'])

    if regclass_exists('public."Partidos"'):
        with op.batch_alter_table('Partidos', schema=None) as batch_op:
            for idx_name in ('ix_partidos_equipo_local_id', 'ix_partidos_equipo_visitante_id'):
                with suppress(Exception):
                    batch_op.drop_index(idx_name)
                with suppress(Exception):
                    batch_op.drop_index(batch_op.f(idx_name))
            for fk_name in ('fk_partidos_equipo_local', 'fk_partidos_equipo_visitante'):
                with suppress(Exception):
                    batch_op.drop_constraint(fk_name, type_='foreignkey')
                with suppress(Exception):
                    batch_op.drop_constraint(batch_op.f(fk_name), type_='foreignkey')
            batch_op.create_foreign_key(None, 'Equipos', ['equipo_local_id'], ['id'])
            batch_op.create_foreign_key(None, 'Equipos', ['equipo_visitante_id'], ['id'])
            batch_op.create_foreign_key(None, 'Clubes', ['club_visitante_id'], ['id'])
            batch_op.create_foreign_key(None, 'Clubes', ['club_local_id'], ['id'])

    if regclass_exists('public."PrecargaJugadoras"'):
        with op.batch_alter_table('PrecargaJugadoras', schema=None) as batch_op:
            for fk_name in ('PrecargaJugadoras_partido_id_fkey', 'PrecargaJugadoras_club_id_fkey', 'PrecargaJugadoras_jugadora_id_fkey'):
                with suppress(Exception):
                    batch_op.drop_constraint(fk_name, type_='foreignkey')
                with suppress(Exception):
                    batch_op.drop_constraint(batch_op.f(fk_name), type_='foreignkey')
            batch_op.create_foreign_key(None, 'Jugadoras', ['jugadora_id'], ['id'])
            batch_op.create_foreign_key(None, 'Partidos', ['partido_id'], ['id'])
            batch_op.create_foreign_key(None, 'Clubes', ['club_id'], ['id'])

    if regclass_exists('public.cuerpo_tecnico_partido'):
        # Inspeccionar existentes para evitar intentar borrar objetos inexistentes
        try:
            uniqs_ctp = {uc['name'] for uc in insp.get_unique_constraints('cuerpo_tecnico_partido', schema='public')}
        except Exception:
            uniqs_ctp = set()
        try:
            cols_ctp = {c['name'] for c in insp.get_columns('cuerpo_tecnico_partido', schema='public')}
        except Exception:
            cols_ctp = set()

        with op.batch_alter_table('cuerpo_tecnico_partido', schema=None) as batch_op:
            batch_op.alter_column('rol',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.String(length=32),
                   existing_nullable=False)
            # El nombre antiguo generado por Alembic suele ser este; sólo borrarlo si existe
            old_uc = 'cuerpo_tecnico_partido_partido_id_club_id_rol_key'
            if old_uc in uniqs_ctp:
                batch_op.drop_constraint(old_uc, type_='unique')
            # Crear el nombre explícito que queremos, sólo si no existe ya
            if 'uq_ct_partido_club_rol' not in uniqs_ctp:
                batch_op.create_unique_constraint('uq_ct_partido_club_rol', ['partido_id', 'club_id', 'rol'])
            # Quitar created_at sólo si la columna existe
            if 'created_at' in cols_ctp:
                batch_op.drop_column('created_at')

    if regclass_exists('public.usuarios'):
        with op.batch_alter_table('usuarios', schema=None) as batch_op:
            # Agregar columnas booleanas con server_default para evitar NOT NULL en filas existentes
            batch_op.add_column(sa.Column('is_operador', sa.Boolean(), nullable=False, server_default=sa.text('false')))
            batch_op.add_column(sa.Column('puede_cargar_incidencias', sa.Boolean(), nullable=False, server_default=sa.text('false')))
            batch_op.add_column(sa.Column('puede_precargar_equipos', sa.Boolean(), nullable=False, server_default=sa.text('false')))
            # Hacer club_id nullable y quitar default 1
            batch_op.alter_column('club_id',
                   existing_type=sa.INTEGER(),
                   nullable=True,
                   server_default=None,
                   existing_server_default=sa.text('1'))

    # Eliminar los server_default de las columnas booleanas para dejarlo como en el modelo
    if regclass_exists('public.usuarios'):
        with op.batch_alter_table('usuarios', schema=None) as batch_op:
            batch_op.alter_column('is_operador', server_default=None, existing_type=sa.Boolean(), existing_nullable=False)
            batch_op.alter_column('puede_cargar_incidencias', server_default=None, existing_type=sa.Boolean(), existing_nullable=False)
            batch_op.alter_column('puede_precargar_equipos', server_default=None, existing_type=sa.Boolean(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('club_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_column('puede_precargar_equipos')
        batch_op.drop_column('puede_cargar_incidencias')
        batch_op.drop_column('is_operador')

    with op.batch_alter_table('cuerpo_tecnico_partido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.drop_constraint('uq_ct_partido_club_rol', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('cuerpo_tecnico_partido_partido_id_club_id_rol_key'), ['partido_id', 'club_id', 'rol'])
        batch_op.alter_column('rol',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('PrecargaJugadoras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('PrecargaJugadoras_jugadora_id_fkey'), 'Jugadoras', ['jugadora_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('PrecargaJugadoras_club_id_fkey'), 'Clubes', ['club_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('PrecargaJugadoras_partido_id_fkey'), 'Partidos', ['partido_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Partidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_partidos_equipo_visitante'), 'Equipos', ['equipo_visitante_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_partidos_equipo_local'), 'Equipos', ['equipo_local_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_partidos_equipo_visitante_id'), ['equipo_visitante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidos_equipo_local_id'), ['equipo_local_id'], unique=False)

    with op.batch_alter_table('NotasPartido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('NotasPartido_partido_id_fkey'), 'Partidos', ['partido_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_notas_partido'), ['partido_id'], unique=False)

    with op.batch_alter_table('Incidencias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Incidencias_jugadora_id_fkey'), 'Jugadoras', ['jugadora_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('Incidencias_partido_id_fkey'), 'Partidos', ['partido_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('Incidencias_club_id_fkey'), 'Clubes', ['club_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_incidencias_partido'), ['partido_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_incidencias_jugadora'), ['jugadora_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_incidencias_club'), ['club_id'], unique=False)

    # ### end Alembic commands ###
