from .club import Club
from .jugadora import Jugadora
from .resultado import Resultado
from .usuario import Usuario
from .incidencia import Incidencia
from .nota_partido import NotaPartido
from .cuerpo_tecnico import CuerpoTecnico
from .cuerpo_tecnico_partido import CuerpoTecnicoPartido
from .arbitro import Arbitro
from .arbitro_partido import ArbitroPartido